simulation:
  timestep: 0.005
  duration: 7
  framerate: 60

robot:
  default_joint_angles: [0.0, 0.9, -1.7, 0.0, 0.9, -1.7, 0.0, 0.9, -1.7, 0.0, 0.9, -1.7]
  kp_custom: [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
  kd_custom: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

actions:
  bounds:
    low: -35.0
    high: 35.0
    special_high: 45.0

scaling:
  body_ang_vel: 0.25
  commands: 2.0
  gravity_body: 1.0
  joint_angles: 1.0
  joint_velocities: 0.05
  actions: 1.0

paths:
  checkpoint_path: nn/SoloTerrain.pth # nn/SoloTerrain_lower_frequency.pth
