policy:
  simulation:
    timestep: 0.005
    duration: 7
    framerate: 60

  robot:
    default_joint_angles: [0.0, 0.9, -1.7, 0.0, 0.9, -1.7, 0.0, 0.9, -1.7, 0.0, 0.9, -1.7]
    Kp_n: 100.0
    Kd_n: 3.0
    max_pos: [1.22,1.8,-0.65,1.22,1.8,-0.65,1.22,1.8,-0.65,1.22,1.8,-0.65]
    min_pos: [-1.22,0.,-2.78,-1.22,0.,-2.78,-1.22,0.,-2.78,-1.22,0.,-2.78]
    torque_values: [-1.6, 0.0, 0.0]
    lim_tau: 40.0
    lim_vel: 26.5

  actions:
    bounds:
      low: -35.0
      high: 35.0
      special_high: 45.0

  scaling:
    body_ang_vel: 0.25
    commands: 2.0
    gravity_body: 1.0
    joint_angles: 1.0
    joint_velocities: 0.05
    actions: 1.0
    factor: 0.5

  paths:
    checkpoint_path: ../nn/SoloTerrain.pth # nn/SoloTerrain_lower_frequency.pth
    value_function: ../nn/VF_safe_MPC_small.pkl

controller:
  robot:
    simulator: False
    joystick: False
    model: ../aliengo_models/xml/aliengo.xml
    decimation: 5
  topics:
    imu: /aliengo_ros/imu
    joint_states: /joint_states
    odometry: /state_estimator_pronto/odom
    command: /command


