settings:
  paths:
    results_folder: ../oct_20/Results_No_MPS_
    force_directions: ../sphere_points_100.csv
    force_iterations: ../aplication_iteration.csv
    robot_models: ../../aliengo_models
    mujoco_model: /xml/aliengo.xml
    pinocchio_model: /urdf/aliengo.urdf
    save_iterations_folder: iterations/
    file_iterations_complete: save_iterations_complete
    file_iterations_no_force: save_iterations_no_force
    file_iterations_force: save_iterations_force
    estimate_lipschitz:
      stop: /Stop_VF_data/data_vf_sensors_stop
      in_place:
        sensors: /InPlace_VF_data/data_vf_sensors_in_place
        state: /MuJoCo_VF_data/data_vf_mujoco
  tests:
    last_test: 0
    torch_num_threads: 1
    torch_num_interop_threads: 1
    stop_force: 20
    threshold_vf: 0.6
    trot_backup: 2
    test_code: False
    visualize: False
    use_mps: False
    manual_mps: False
    estimate_lipschitz: False
    vf_always: False
    save_data: True
    save_iterations: False
    force_mag: [200, 115 ] #, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195]
    backup:
      stop: False
      in_place:
        sensors: True
        state: False
    
simulation:
  timestep_simulation: 0.002
  duration: 7
  framerate: 60

robot:
  backup:
    default_joint_angles: [0.0, 0.9, -1.7, 0.0, 0.9, -1.7, 0.0, 0.9, -1.7, 0.0, 0.9, -1.7]
    kp: [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
    kd: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
  nominal:
    default_joint_angles: [0.0, 0.9, -1.8, 0.0, 0.9, -1.8, 0.0, 0.9, -1.8, 0.0, 0.9, -1.8]
    kp: [21.5, 21.5, 21.5, 21.5, 21.5, 21.5, 21.5, 21.5, 21.5, 21.5, 21.5, 21.5]
    kd: [3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5]

env_nominal:
  action_scale: 0.5
  decimation: 5
  dt: 0.002
  desired_clip_actions: 3.0
  order: [0, 6, 3, 9, 1, 7, 4, 10, 2, 8, 5, 11]

actions:
  bounds:
    low: -35.0
    high: 35.0
    special_high: 45.0

scaling_backup:
  body_ang_vel: 0.25
  commands: 2.0
  gravity_body: 1.0
  joint_angles: 1.0
  joint_velocities: 0.05
  actions: 1.0
  q_des: 0.5

networks:
  paths:
    trot_backup1: trot_backup1.pth
    trot_backup2: trot_backup2.pth
    stop: stop.pt
    nominal: aliengo.pt
    state_estimator: cuncurrent_state_estimator.pth
    vf_state_in_place: vf/VF_state_in_place.pkl
    vf_sensors_in_place: vf/VF_sensors_in_place.pkl
    vf_sensors_stop: vf/VF_sensors_stop.pkl
  device: cpu

stop:
  robot:
    Kp_b: 25
    Kd_b: 0.5
    torque_limit: 40.0
    vel_limit: 26.5

  scaling:
    running_mean: [  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.21205050e+00,
                    -8.06230644e-03, -1.42328272e+00,  1.00789203e-01, -1.14620532e-01,
                     6.92671321e-02, -2.20188718e-01,  2.29067680e-01,  2.09180188e-01,
                     2.06069022e-01,  1.45354481e-01, -4.06120459e-01, -4.48609024e-01,
                    -3.88464357e-01, -3.97695643e-01, -6.33672667e-03, -1.95075319e-03,
                    -3.96507459e-03, -4.42201867e-02,  1.14105612e-01,  1.03970752e-01,
                     5.92749748e-02,  4.45349231e-02, -1.63696425e-01, -1.79439128e-01,
                    -1.44850614e-01, -1.38541725e-01,  3.80852309e-02, -1.01241193e-01,
                    -1.90169735e-02, -1.39184525e-01,  1.36771685e-01,  1.38808689e-01,
                     1.64408062e-01,  1.45937922e-01,  4.67878538e-02, -5.74250520e-04,
                    -6.52443376e-02, -1.06306087e-02]
    running_variance: [1.45321798e-08, 1.45321798e-08, 1.45321798e-08, 1.02176822e+01,
                       1.08386133e+01, 2.91442128e+01, 6.12955153e-02, 7.91401819e-02,
                       6.40535954e-02, 3.81343809e-02, 8.86714353e-02, 6.60074706e-02,
                       5.39578640e-02, 3.24022101e-02, 5.45107210e-02, 5.66611032e-02,
                       6.45901655e-02, 6.92300715e-02, 6.07200216e+00, 5.75513999e+00,
                       8.04183510e+00, 8.15766779e+00, 4.10619267e+00, 4.09391329e+00,
                       5.59485546e+00, 5.44709528e+00, 6.09915664e+00, 6.84910827e+00,
                       9.67759842e+00, 8.53798207e+00, 7.66597364e-02, 7.27123376e-02,
                       8.60715622e-02, 6.56937354e-02, 8.89956898e-02, 8.91989478e-02,
                       8.37767829e-02, 6.97930652e-02, 1.43025920e-01, 1.22080731e-01,
                       1.49352419e-01, 1.33925065e-01]
    epsilon: 1.0e-8
    clip_threshold: 5.0
    default_joint_angles: [0.1, -0.1,  0.1, -0.1,  0.8,  0.8, 1.0,  1.0, -1.5, -1.5, -1.5, -1.5]
    factor: 0.8

  dictionary:
    old_keys: [net.0.weight, net.0.bias,      net.2.weight,      net.2.bias,
               net.4.weight, net.4.bias, mean_layer.weight, mean_layer.bias] 
    new_keys: [layers.0.weight, layers.0.bias, layers.2.weight, layers.2.bias,
               layers.4.weight, layers.4.bias, layers.6.weight, layers.6.bias]

controller:
  topics:
    imu: /aliengo/trunk_imu
    joint_states: /aliengo/joint_states
    odometry: /aliengo/ground_truth
    pose: /pronto/pose
    twist: /pronto/twist